config/routes.rb
Rails.application.routes.draw do
root 'qkls#index'
  resources :qkls do
    member do
      post 'upvote'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/qkl.rb
class Qkl < ApplicationRecord
has_many :votes,dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
belongs_to :qkl
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/qkls_controller.rb
class QklsController < ApplicationController
  before_action :set_qkl, only: [:show, :edit, :update, :destroy]

  # GET /qkls
  # GET /qkls.json
  def index
    @qkls = Qkl.all
  end

  # GET /qkls/1
  # GET /qkls/1.json
  def show
  end

  # GET /qkls/new
  def new
    @qkl = Qkl.new
  end

  # GET /qkls/1/edit
  def edit
  end

  # POST /qkls
  # POST /qkls.json
  def create
    @qkl = Qkl.new(qkl_params)

    respond_to do |format|
      if @qkl.save
        format.html { redirect_to qkls_path, notice: 'Qkl was successfully created.' }
        format.json { render :show, status: :created, location: @qkl }
      else
        format.html { render :new }
        format.json { render json: @qkl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qkls/1
  # PATCH/PUT /qkls/1.json
  def update
    respond_to do |format|
      if @qkl.update(qkl_params)
        format.html { redirect_to qkls_path, notice: 'Qkl was successfully updated.' }
        format.json { render :show, status: :ok, location: @qkl }
      else
        format.html { render :edit }
        format.json { render json: @qkl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qkls/1
  # DELETE /qkls/1.json
  def destroy
    @qkl.destroy
    respond_to do |format|
      format.html { redirect_to qkls_url, notice: 'Qkl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @qkl = Qkl.find(params[:id])
    @qkl.votes.create
    redirect_to(qkls_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qkl
      @qkl = Qkl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qkl_params
      params.require(:qkl).permit(:xuexi, :jianxing)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qkls_helper.rb
module QklsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Feiben</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qkls/_form.html.erb
<%= form_for(qkl) do |f| %>
  <% if qkl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(qkl.errors.count, "error") %> prohibited this qkl from being saved:</h2>

      <ul>
      <% qkl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :xuexi %>
    <%= f.text_field :xuexi %>
  </div>

  <div class="field">
    <%= f.label :jianxing %>
    <%= f.text_area :jianxing %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/qkls/edit.html.erb
<h1>Editing Qkl</h1>

<%= render 'form', qkl: @qkl %>

<%= link_to 'Show', @qkl %> |
<%= link_to 'Back', qkls_path %>

app/views/qkls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Qkls</h1>

<table>
  <thead>
    <tr>
      <th>Xuexi</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @qkls.each do |qkl| %>
      <tr>
        <td><%= link_to qkl.xuexi ,qkl%></td>

        <td><%= pluralize(qkl.votes.count,"vote") %></td>
        <td><%= button_to '+1',upvote_qkl_path(qkl),method: :post %></td>

        <td><%= link_to 'Delete', qkl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qkl', new_qkl_path %>

app/views/qkls/new.html.erb
<h1>New Qkl</h1>

<%= render 'form', qkl: @qkl %>

<%= link_to 'Back', qkls_path %>

app/views/qkls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Xuexi:</strong>
  <%= @qkl.xuexi %>
</p>

<p>
  <strong>Jianxing:</strong>
  <%= @qkl.jianxing %>
</p>

<%= link_to 'Edit', edit_qkl_path(@qkl) %> |
<%= link_to 'Back', qkls_path %>